name: Publish

on:
  push:
    branches: [ master, develop ]

jobs:
  # Fazer a build, sempre, para todas as branches
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: "Extract Branch name"
      run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: "Login to GitHub registry"
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: "Publish the image"
      uses: docker/build-push-action@v2
      with:
        file: ./src/CellCms.Api/Dockerfile
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/cell-cms:${{ github.sha }}
          ghcr.io/${{ github.repository }}/cell-cms:${{ env.BRANCH }}
